# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 01:53
from __future__ import unicode_literals

import ao.upcloud.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField()),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('api_key', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('address', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('access', models.CharField(choices=[('private', 'private'), ('public', 'public')], max_length=7)),
                ('family', models.CharField(choices=[('IPv4', 'IPv4'), ('IPv6', 'IPv6')], max_length=4)),
                ('part_of_plan', models.BooleanField(default=False)),
                ('ptr_record', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'IP addresses',
                'verbose_name': 'IP address',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('core_number', models.SmallIntegerField()),
                ('memory_amount', models.SmallIntegerField()),
                ('public_traffic_out', models.SmallIntegerField()),
                ('storage_size', models.SmallIntegerField()),
                ('storage_tier', models.CharField(choices=[('hdd', 'hdd'), ('maxiops', 'maxiops')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('hostname', models.CharField(max_length=128)),
                ('licence', models.SmallIntegerField(blank=True, default=0)),
                ('core_number', models.SmallIntegerField(blank=True)),
                ('memory_amount', models.SmallIntegerField(blank=True)),
                ('state', models.CharField(blank=True, choices=[('started', 'started'), ('stopped', 'stopped'), ('maintenance', 'maintenance'), ('error', 'error')], default='started', max_length=11)),
                ('firewall', models.BooleanField(default=True)),
                ('boot_order', models.CharField(blank=True, default='disk', max_length=10)),
                ('host', models.IntegerField(blank=True, default=ao.upcloud.models.random_host_id)),
                ('nic_model', models.CharField(blank=True, choices=[('e1000', 'e1000'), ('virtio', 'virtio'), ('rtl8139', 'rtl8139')], default='e1000', max_length=7)),
                ('timezone', models.CharField(max_length=40)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upcloud.Account')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upcloud.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('access', models.CharField(blank=True, choices=[('private', 'private'), ('public', 'public')], max_length=7)),
                ('type', models.CharField(blank=True, choices=[('normal', 'normal'), ('backup', 'backup'), ('cdrom', 'cdrom'), ('template', 'template')], max_length=8)),
                ('tier', models.CharField(blank=True, choices=[('hdd', 'hdd'), ('maxiops', 'maxiops')], default='hdd', max_length=7)),
                ('size', models.SmallIntegerField()),
                ('license', models.SmallIntegerField(blank=True, default=0)),
                ('part_of_plan', models.BooleanField()),
                ('backup_rule_interval', models.CharField(blank=True, choices=[('daily', 'daily'), ('mon', 'mon'), ('tue', 'tue'), ('wed', 'wed'), ('thu', 'thu'), ('fri', 'fri'), ('sat', 'sat'), ('sun', 'sun')], max_length=5, null=True)),
                ('backup_rule_time', models.CharField(blank=True, max_length=4, null=True)),
                ('backup_rule_retention', models.SmallIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, choices=[('online', 'online'), ('maintenance', 'maintenance'), ('cloning', 'cloning'), ('backuping', 'backuping'), ('error', 'error')], default='maintenance', max_length=11)),
                ('address', models.CharField(blank=True, max_length=15, null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upcloud.Account')),
                ('backup_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upcloud.Storage')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upcloud.Server')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('servers', models.ManyToManyField(to='upcloud.Server')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.SlugField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='storage',
            name='zone',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='upcloud.Zone'),
        ),
        migrations.AddField(
            model_name='server',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upcloud.Zone'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upcloud.Server'),
        ),
    ]
