# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='firewall_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='io_request_backup_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='io_request_hdd_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='io_request_maxiops_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='ipv4_address_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='ipv6_address_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='plan_12cpu_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='plan_16cpu_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='plan_1cpu_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='plan_20cpu_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='plan_2cpu_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='plan_4cpu_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='plan_6cpu_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='plan_8cpu_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='public_ipv4_bandwidth_in_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='public_ipv4_bandwidth_out_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='public_ipv6_bandwidth_in_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='public_ipv6_bandwidth_out_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='server_core_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='server_memory_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='storage_backup_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='storage_hdd_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='storage_maxiops_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='windows_datacenter_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='windows_standard_price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
            preserve_default=False,
        ),
    ]
