# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcloud', '0003_auto_20180122_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='public_ipv4_bandwidth_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zone',
            name='public_ipv4_bandwidth_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zone',
            name='public_ipv6_bandwidth_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zone',
            name='public_ipv6_bandwidth_out',
            field=models.IntegerField(default=0),
        ),
    ]
