# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upcloud', '0004_auto_20180122_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('accept', 'accept'), ('drop', 'drop')], max_length=6)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('destination_address_start', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_address_end', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_port_start', models.PositiveIntegerField(blank=True, null=True)),
                ('destination_port_end', models.PositiveIntegerField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=3)),
                ('family', models.CharField(choices=[('IPv4', 'IPv4'), ('IPv6', 'IPv6')], max_length=4)),
                ('icmp_type', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, choices=[('tcp', 'tcp'), ('udp', 'udp'), ('icmp', 'icmp')], max_length=4, null=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_address_start', models.GenericIPAddressField(blank=True, null=True)),
                ('source_address_end', models.GenericIPAddressField(blank=True, null=True)),
                ('source_port_start', models.PositiveIntegerField(blank=True, null=True)),
                ('source_port_end', models.PositiveIntegerField(blank=True, null=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upcloud.Server')),
            ],
            options={
                'verbose_name_plural': 'Firewall rule',
                'verbose_name': 'Firewall rule',
            },
        ),
    ]
