from ao import settings

def get_setting(name, default):
    name = 'UPCLOUD_' + name
    return getattr(settings, name, default)


AUTHENTICATION_LEVEL = get_setting('AUTHENTICATION_LEVEL', 0)
CREATION_LEVEL = get_setting('AUTHENTICATION_LEVEL', 0)

SERVER_ACCESS_LEVEL = get_setting('SERVER_ACCESS_LEVEL', 0)
SERVER_ACTION_LEVEL = get_setting('SERVER_ACTION_LEVEL', 0)
SERVER_STOP_DELAY = get_setting('SERVER_STOP_DELAY', 1)
SERVER_START_DELAY = get_setting('SERVER_RESTART_DELAY', 1)
SERVER_RESTART_DELAY = get_setting('SERVER_RESTART_DELAY', 1)

IP_ADDRESS_ACCESS_LEVEL = get_setting('IP_ADDRESS_ACCESS_LEVEL', 0)
IP_ADDRESS_ACTION_LEVEL = get_setting('IP_ADDRESS_ACTION_LEVEL', 0)

FIREWALL_RULE_ACCESS_LEVEL = get_setting('FIREWALL_RULE_ACCESS_LEVEL', 0)
FIREWALL_RULE_ACTION_LEVEL = get_setting('FIREWALL_RULE_ACTION_LEVEL', 0)

STORAGE_ACCESS_LEVEL = get_setting('STORAGE_ACCESS_LEVEL', 0)
STORAGE_ACTION_LEVEL = get_setting('STORAGE_ACTION_LEVEL', 0)
STORAGE_INITIALIZE_DELAY = get_setting('STORAGE_INITIALIZE_DELAY', 0)
STORAGE_MODIFY_DELAY = get_setting('STORAGE_MODIFY_DELAY', 0)
STORAGE_CLONE_DELAY = get_setting('STORAGE_CLONE_DELAY', 0)
STORAGE_BACKUP_DELAY = get_setting('STORAGE_BACKUP_DELAY', 0)
STORAGE_TEMPLATIZE_DELAY = get_setting('STORAGE_TEMPLATIZE_DELAY', 0)
