# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvaibilitySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[(b'eastus', b'eastus'), (b'westus', b'westus')], max_length=20)),
                ('os_type', models.CharField(blank=True, max_length=20, null=True)),
                ('vhd_uri', models.CharField(max_length=255)),
                ('caching', models.CharField(choices=[(b'None', b'None'), (b'ReadOnly', b'ReadOnly'), (b'ReadWrite', b'ReadWrite')], max_length=10)),
                ('create_option', models.CharField(choices=[(b'fromImage', b'fromImage'), (b'attach', b'attach')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ImageOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePublisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[(b'eastus', b'eastus'), (b'westus', b'westus')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImageSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msazure.ImageOffer')),
            ],
        ),
        migrations.CreateModel(
            name='ImageVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msazure.ImageSku')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StorageAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(choices=[(b'Standard_LRS', b'Standard_LRS'), (b'Standard_ZRS', b'Standard_ZRS'), (b'Standard_GRS', b'Standard_GRS'), (b'Standard_RAGRS', b'Standard_RAGRS'), (b'Premium_LRS', b'Premium_LRS')], max_length=30)),
                ('kind', models.CharField(choices=[(b'Storage', b'Storage'), (b'BlobStorage', b'BlobStorage')], max_length=30)),
                ('access_tier', models.CharField(choices=[(b'Cool', b'Cool'), (b'Hot', b'Hot')], max_length=30)),
                ('tags', models.TextField(default=b'{}', max_length=2000)),
                ('resource_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msazure.ResourceGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[(b'eastus', b'eastus'), (b'westus', b'westus')], max_length=20)),
                ('tags', models.TextField(default=b'{}', max_length=2000)),
                ('provisioning_state', models.CharField(max_length=20)),
                ('vm_size', models.CharField(max_length=30)),
                ('computer_name', models.CharField(max_length=100)),
                ('admin_username', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=100)),
                ('custom_data', models.TextField(max_length=100)),
                ('avaibility_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msazure.AvaibilitySet')),
                ('data_disks', models.ManyToManyField(to='msazure.Disk')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msazure.ImageVersion')),
                ('network_interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msazure.NetworkInterface')),
                ('os_disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_on_instances', to='msazure.Disk')),
                ('resource_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msazure.ResourceGroup')),
            ],
        ),
        migrations.AddField(
            model_name='resourcegroup',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msazure.Subscription'),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='resource_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msazure.ResourceGroup'),
        ),
        migrations.AddField(
            model_name='imageoffer',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msazure.ImagePublisher'),
        ),
        migrations.AddField(
            model_name='disk',
            name='resource_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msazure.ResourceGroup'),
        ),
        migrations.AddField(
            model_name='disk',
            name='storage_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msazure.StorageAccount'),
        ),
        migrations.AddField(
            model_name='avaibilityset',
            name='resource_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msazure.ResourceGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='virtualmachine',
            unique_together=set([('name', 'resource_group')]),
        ),
    ]
